name: momentum
description: "Momentum is a simple, focused task management app built to help you turn plans into progress."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  connectivity_plus: ^7.3.1
  flex_color_picker: ^4.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.3
  path: ^1.9.1
  shared_preferences: ^2.5.5
  uuid: ^4.6.0
  sqflite: ^2.4.3
  flutter_dotenv: ^6.0.1
  dio: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  #  icons_launcher: ^3.1.0
  flutter_svg: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Medium.otf
          weight: 500
        - asset: assets/fonts/Cera-Pro-Bold.otf
          weight: 700

#icons_launcher:
#  image_path: "assets/icons/app_icon.png"
#
#  platforms:
#    android:
#      enable: true
#
#    ios:
#      enable: true